openapi: 3.0.0
info:
  title: AlleReach Azure DB API
  description: An API to retrieve AlleReach Orders from database using Express
  version: 1.0.0

servers:
  - url: http://localhost:1433
    description: Local development server

paths:
  /orders:
    get:
      summary: Get orders
      description: Retrieves orders from the database
      parameters:
        - name: x-api-key
          in: header
          description: API Key for authentication
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  orders:
                    type: array
                    items:
                      $ref: '#/components/schemas/Order'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
components:
  schemas:
    Order:
      type: object
      properties:
        RecordID:
          type: string
          format: uuid
        LastUpdate:
          type: string
          format: date-time
        archived:
          type: boolean
        FillID:
          type: string
          format: uuid
        FillLastUpdate:
          type: string
          format: date-time
        Pharmacy_NPI:
          type: string
          pattern: '^[0-9]{10}$'
        Rx_Number:
          type: string
        Rx_Fill_Number:
          type: string
        Formula_Number:
          type: string
        Drug_Count:
          type: integer
        Quantity_Prescribed:
          type: number
        Sig:
          type: string
        Daw:
          type: integer
        Facilitator_Code:
          type: string
          nullable: true
        Rx_Origin:
          type: string
        Rx_Refills:
          type: integer
        Rx_Refills_Remaining:
          type: integer
        Refill_On_Hold:
          type: string
          enum:
            - Yes
            - No
        Expiration_Date:
          type: string
          format: date-time
        Rx_Written_Date:
          type: string
          format: date-time
        Follow_Up_Date:
          type: string
          format: date-time
          nullable: true
        Last_Refill_Request_Fax_Sent_Date:
          type: string
          format: date-time
          nullable: true
        Last_Prior_Auth_Fax_Sent_Date:
          type: string
          format: date-time
          nullable: true
        Rx_On_Hold:
          type: string
          enum:
            - Yes
            - No
        Rx_On_Hold_Reason:
          type: string
          nullable: true
        Rx_On_Hold_Note:
          type: string
          nullable: true
        Epcs_Prescription:
          type: string
          enum:
            - Yes
            - No
        Epcs_Reference_Number:
          type: string
          nullable: true
        Epcs_Order_Number:
          type: string
          nullable: true
        Drug_Prescribed_Type:
          type: string
        Drug_Prescribed_Name:
          type: string
        Drug_Prescribed_Generic_Name:
          type: string
          nullable: true
        Drug_Prescribed_Strength:
          type: string
        Drug_Prescribed_Form:
          type: string
        Drug_Prescribed_Schedule_Name:
          type: string
        Drug_Prescribed_Unit:
          type: string
        Drug_Prescribed_Admin_Route:
          type: string
        Drug_Prescribed_Therapeutic_Class:
          type: string
          nullable: true
        Drug_Dispensed_Type:
          type: string
        Drug_Dispensed_Name:
          type: string
        Drug_Dispensed_Generic_Name:
          type: string
          nullable: true
        Drug_Dispensed_Strength:
          type: string
        Drug_Dispensed_Form:
          type: string
        Drug_Dispensed_Schedule_Name:
          type: string
        Drug_Dispensed_Unit:
          type: string
        Drug_Dispensed_Admin_Route:
          type: string
        Drug_Dispensed_Therapeutic_Class:
          type: string
          nullable: true
        Is_Vet_Rx:
          type: string
          enum:
            - Yes
            - No
        Vet_First_Name:
          type: string
          nullable: true
        Vet_Last_Name:
          type: string
          nullable: true
        Vet_Middle_Name:
          type: string
          nullable: true
        Vet_Dea:
          type: string
          nullable: true
        Vet_Practice_Type_Description:
          type: string
          nullable: true
        Vet_Practice_Type_Group_Code:
          type: string
          nullable: true
        Vet_Address_Line_1:
          type: string
          nullable: true
        Vet_Address_Line_2:
          type: string
          nullable: true
        Vet_City:
          type: string
          nullable: true
        Vet_State:
          type: string
          nullable: true
        Vet_Zip:
          type: string
          nullable: true
        Vet_Phone_1:
          type: string
          nullable: true
        Vet_Phone_2:
          type: string
          nullable: true
        Vet_Fax:
          type: string
          nullable: true
        Patient_ID:
          type: integer
        Patient_Reference_ID:
          type: string
          nullable: true
        Patient_First_Name:
          type: string
        Patient_Last_Name:
          type: string
        Patient_Middle_Name:
          type: string
          nullable: true
        Patient_Gender:
          type: string
          nullable: true
        Patient_Birthday:
          type: string
          format: date-time
        Patient_Email:
          type: string
          nullable: true
        Patient_Is_Smoker:
          type: string
          enum:
            - Yes
            - No
        Patient_Is_Pregnant:
          type: string
          enum:
            - Yes
            - No
        Patient_Prefers_Safety_Cap:
          type: string
          enum:
            - Yes
            - No
        Patient_Use_Generics:
          type: string
          enum:
            - Yes
            - No
        Patient_Print_Pal:
          type: string
          enum:
            - Yes
            - No
        Patient_Is_Deceased:
          type: string
          enum:
            - Yes
            - No
        Patient_Weight:
          type: number
          nullable: true
        Patient_Phone_Number:
          type: string
          nullable: true
        Patient_Phone_Type:
          type: string
          nullable: true
        Patient_Bill_Address_1:
          type: string
          nullable: true
        Patient_Bill_Address_2:
          type: string
          nullable: true
        Patient_Bill_City:
          type: string
          nullable: true
        Patient_Bill_State:
          type: string
          nullable: true
        Patient_Bill_Zip:
          type: string
          nullable: true
        Patient_Ship_Address_1:
          type: string
          nullable: true
        Patient_Ship_Address_2:
          type: string
          nullable: true
        Patient_Ship_City:
          type: string
          nullable: true
        Patient_Ship_State:
          type: string
          nullable: true
        Patient_Ship_Zip:
          type: string
          nullable: true
        Rx_Prescriber_ID:
          type: string
          format: uuid
        Rx_Prescriber_Last_Name:
          type: string
        Rx_Prescriber_First_Name:
          type: string
        Rx_Prescriber_Middle_Name:
          type: string
          nullable: true
        Rx_Prescriber_DEA_Last_Name:
          type: string
          nullable: true
        Rx_Prescriber_DEA_First_Name:
          type: string
          nullable: true
        Rx_Prescriber_DEA_Middle_Name:
          type: string
          nullable: true
        Rx_Prescriber_DEA_Dea_Number:
          type: string
          nullable: true
        Rx_Prescriber_DEA_State:
          type: string
          nullable: true
        Rx_Prescriber_NPI_Last_Name:
          type: string
        Rx_Prescriber_NPI_First_Name:
          type: string
        Rx_Prescriber_NPI_Middle_Name:
          type: string
          nullable: true
        Rx_Prescriber_NPI_NPI:
          type: string
        Rx_Prescriber_NPI_Practice_Type:
          type: string
        Rx_Prescriber_NPI_Address_1:
          type: string
          nullable: true
        Rx_Prescriber_NPI_Address_2:
          type: string
          nullable: true
        Rx_Prescriber_NPI_City:
          type: string
          nullable: true
        Rx_Prescriber_NPI_State:
          type: string
          nullable: true
        Rx_Prescriber_NPI_Zip:
          type: string
          nullable: true
        Rx_Prescriber_NPI_Phone:
          type: string
          nullable: true
        Rx_Fill_Date:
          type: string
          nullable: true
        Rx_Fill_Rx_Due_Date:
          type: string
          nullable: true
        Rx_Fill_Sold_Date:
          type: string
          nullable: true
        Rx_Fill_Discard_After_Date:
          type: string
          nullable: true
        Rx_Fill_Validation_Date:
          type: string
          nullable: true
        Rx_Fill_Ship_Date:
          type: string
        Rx_Fill_Tracking_Number:
          type: string
        Rx_Fill_Shipping_Carrier_Name:
          type: string
        Rx_Fill_Shipping_Carrier_Type:
          type: string
        Rx_Fill_Shipping_Package_Type:
          type: string
        Rx_Fill_Shipping_Weight:
          type: string
        Rx_Fill_Shipping_UOM:
          type: string
        Rx_Fill_Last_SMS_Sent_Date:
          type: string
          nullable: true
        Rx_Fill_Delivery_Method:
          type: string
        Rx_Fill_Remaining_Refills:
          type: integer
        Rx_Fill_Days_Supply:
          type: integer
        Rx_Fill_Is_Cyclic:
          type: string
          enum:
            - Yes
            - No
        Rx_Fill_Is_Barcode_Checked:
          type: string
          enum:
            - Yes
            - No
        Rx_Fill_Is_Price_Locked:
          type: string
          enum:
            - Yes
            - No
        Rx_Fill_Did_Validation_Fail:
          type: string
          enum:
            - Yes
            - No
        Rx_Fill_Failed_Validation_Tech_Last_Name:
          type: string
          nullable: true
        Rx_Fill_Failed_Validation_Tech_First_Name:
          type: string
          nullable: true
        Rx_Fill_Failed_Validation_Tech_Middle_Name:
          type: string
          nullable: true
        Rx_Fill_Current_State:
          type: string
        Rx_Current_State:
          type: string
        Rx_Fill_Detail_Current_State:
          type: string
        Rx_Pricing_Schedule:
          type: string
          nullable: true
        Rx_Fill_Total_Price:
          type: number
        Rx_Fill_Total_Cost:
          type: number
        Rx_Fill_Patient_Price:
          type: number
        Rx_Fill_Quantity:
          type: number
        Rx_Fill_Pharmacist_Last_Name:
          type: string
        Rx_Fill_Pharmacist_First_Name:
          type: string
        Rx_Fill_Pharamcist_Middle_Name:
          type: string
          nullable: true
        Rx_Fill_Technician_Last_Name:
          type: string
          nullable: true
        Rx_Fill_Technician_First_Name:
          type: string
          nullable: true
        Rx_Fill_Technician_Middle_Name:
          type: string
          nullable: true



